import { createClient } from '@supabase/supabase-js';

const supabaseUrl = 'https://shbkbmkbvktozaargrpz.supabase.co';
// WARNING: This key is publicly visible. Ensure you have Row Level Security (RLS) enabled on your tables.
const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNoYmtibWtidmt0b3phYXJncnB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIyMzI1NjMsImV4cCI6MjA3NzgwODU2M30.rbuzJ_5_xQlAMQZCbz8N4ckTo6jKgujbXnH176XbzOw';

export const supabase = createClient(supabaseUrl, supabaseAnonKey);

/*
================================================================================
==! IMPORTANT: RUN THIS SQL SCRIPT IN YOUR SUPABASE SQL EDITOR               !==
================================================================================

This script will set up all the necessary tables, storage, security policies,
and functions for the OSIS Portal application to work correctly.

-- 1. Create storage buckets for voice notes, event images, chat images, and avatars
-- Make sure to set policies on these buckets in the Supabase Dashboard
-- For example, allow authenticated users to upload/download.
insert into storage.buckets (id, name, public)
values 
  ('voice_notes', 'voice_notes', true),
  ('event_images', 'event_images', true),
  ('chat_images', 'chat_images', true),
  ('avatars', 'avatars', true)
on conflict (id) do nothing;


-- 2. Create PROFILES table to store user data
create table if not exists public.profiles (
  id uuid not null primary key references auth.users(id) on delete cascade,
  full_name text,
  avatar_url text,
  role text default 'member'
);
comment on table public.profiles is 'Stores public profile information for each user.';


-- 3. Create CHANNELS table for chat
create table if not exists public.channels (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
comment on table public.channels is 'Stores chat channels.';

-- Create a default "general" channel if it doesn't exist
insert into public.channels (name)
select 'general'
where not exists (select 1 from public.channels where name = 'general');


-- 4. Create MESSAGES table for chat
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  content text,
  user_id uuid not null references auth.users(id) on delete cascade,
  channel_id bigint not null references public.channels(id) on delete cascade,
  type text default 'text'
);
comment on table public.messages is 'Stores chat messages for each channel.';


-- 5. Create EVENTS table for OSIS agenda/events
create table if not exists public.events (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  event_date timestamp with time zone not null,
  created_by uuid references auth.users(id) on delete set null
);
comment on table public.events is 'Stores OSIS events and agendas.';


-- 6. Function to create a profile for a new user
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$;


-- 7. Trigger to call the function when a new user signs up
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- 8. Set up Row Level Security (RLS)
-- Make sure RLS is enabled for all tables in the Supabase dashboard.

-- PROFILES RLS
alter table public.profiles enable row level security;
drop policy if exists "Users can view all profiles." on public.profiles;
create policy "Users can view all profiles." on public.profiles for select using (auth.role() = 'authenticated');

drop policy if exists "Users can update their own profile." on public.profiles;
create policy "Users can update their own profile." on public.profiles for update using (auth.uid() = id);

drop policy if exists "Admins can update any profile." on public.profiles;
create policy "Admins can update any profile." on public.profiles for update with check (
  (select role from public.profiles where id = auth.uid()) = 'admin'
);

-- CHANNELS RLS
alter table public.channels enable row level security;
drop policy if exists "Authenticated users can view all channels." on public.channels;
create policy "Authenticated users can view all channels." on public.channels for select using (auth.role() = 'authenticated');

drop policy if exists "Admins can create channels." on public.channels;
create policy "Admins can create channels." on public.channels for insert with check (
  (select role from public.profiles where id = auth.uid()) = 'admin'
);

-- MESSAGES RLS
alter table public.messages enable row level security;
drop policy if exists "Authenticated users can view all messages." on public.messages;
create policy "Authenticated users can view all messages." on public.messages for select using (auth.role() = 'authenticated');

drop policy if exists "Users can insert their own messages." on public.messages;
create policy "Users can insert their own messages." on public.messages for insert with check (auth.uid() = user_id);

-- EVENTS RLS
alter table public.events enable row level security;
drop policy if exists "Authenticated users can view all events." on public.events;
create policy "Authenticated users can view all events." on public.events for select using (auth.role() = 'authenticated');

drop policy if exists "Admins can create events." on public.events;
create policy "Admins can create events." on public.events for insert with check (
  (select role from public.profiles where id = auth.uid()) = 'admin'
);

drop policy if exists "Admins can update or delete events." on public.events;
create policy "Admins can update or delete events." on public.events for all using (
  (select role from public.profiles where id = auth.uid()) = 'admin'
);

*/